name: poc_encriptacion
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.5

# Add regular dependencies here.
dependencies:
  basic_utils: ^5.6.0
  crypto_keys: ^0.3.0+1
  cryptography: ^2.5.0
  http: ^1.1.0
  pointycastle: ^3.7.3
  convert: ^3.0.0
  encrypt: ^5.0.1
  aes256gcm: ^1.0.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
